version: '3.9'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    security_opt:
      - no-new-privileges
    restart: unless-stopped
  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/database
    security_opt:
      - no-new-privileges
    restart: unless-stopped
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    volumes:
      - db-data:/var/lib/postgresql/data
    security_opt:
      - no-new-privileges
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    security_opt:
      - no-new-privileges
    restart: unless-stopped
  worker:
    build: ./worker
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    security_opt:
      - no-new-privileges
    restart: unless-stopped

volumes:
  db-data: