name: Deploy Terraform and Ansible 🚀

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 📁
        uses: actions/checkout@v2

      - name: Login to AWS 🔒
        uses: aws-actions/login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install Terraform 📦
        run: |
          sudo apt-get update
          sudo apt-get install -y terraform

      - name: Initialize Terraform 💻
        run: terraform init

      - name: Apply Terraform 🚀
        run: terraform apply -auto-approve

      - name: Output Terraform state 📊
        run: terraform output

      - name: Install Ansible 📦
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible playbook 📝
        run: ansible-playbook -i <path_to_inventory_file> <path_to_playbook_file>